### ISSUE TITLE
dist is no longer ES5

### ISSUE THREAD

**Issue by afhole** [oflisback/react-favicon#10]
The dist build now seems to be no longer just ES5, so now needs processing with babel.
Is this by design? Most modules on npm provide an ES5 compatible dist bundle

**Comment by afhole** [comment]
Also it seems that it is using babel stage 1, so anyone using this would also have to build with stage 1

**Comment by afhole** [comment]
Did you run the code mod on dist? Does it just need building again?

**Comment by afhole** [comment]
I think it just needs babel-preset-es2015, I will do a PR

**Comment by afhole** [comment]
Hi @oflisback, @cezary - would really appreciate it if someone has time to review this? Thanks 👍

**Comment by oflisback** [comment]
Thank you, I'll get back to you later today!

**Comment by oflisback** [comment]
Thank you @afhole!

**Comment by afhole** [comment]
Awesome, thanks for getting back so quickly :)
