### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by emko4** [oflisback/react-favicon#17]
The peerDependency is for ~16.0.0, but there isn't new release, so npm download old version with 
`"peerDependencies": {
    "react": ">=0.12.0 <= ^15.5.4"
  }`

**Comment by oflisback** [comment]
I'm not sure I follow, there is a 16.0.0 react release. When I:

1. clone the repo
2. npm install
3. npm install react (to get the peer dependency)

I receive react 16.0.0 as a dependency. Can you clarify please?

**Comment by emko4** [comment]
When I add `"react-favicon": "0.0.9"` (last release) to my project `package.json`, I have in node-modules version with
`"peerDependencies": {
    "react": ">=0.12.0 <= ^15.5.4"
  },`

**Comment by oflisback** [comment]
Thanks a lot you are right, I've published an updated version to the npm registry now.

**Comment by emko4** [comment]
I'm sorry, it's me again :), but could you change peerDependencies from
`"peerDependencies": { "react": ">=0.12.0 <= ~16.0.0" }` to `"peerDependencies": { "react": ">=0.12.0 <= ^16.0.0" }` ?
Because React 16.1.0 was realesed yesterday and I still have warning during npm install (yarn install). 

Thans a lot :)

**Comment by oflisback** [comment]
Thank you, done!
