### ISSUE TITLE
`alertCount` only correctly renders on 16x16 favicons

### ISSUE THREAD

**Issue by christiangenco** [oflisback/react-favicon#18]
On [the react-favicon examples page](http://oflisback.github.io/react-favicon/), the `alertCount` prop displays correctly on the 16x16 nyancat favicon:

<img width="86" alt="screen shot 2018-01-18 at 1 34 45 pm" src="https://user-images.githubusercontent.com/179361/35117548-95f50936-fc54-11e7-852a-cf754a21c853.png">

but not the github favicon (32x32):

<img width="89" alt="screen shot 2018-01-18 at 1 34 37 pm" src="https://user-images.githubusercontent.com/179361/35117554-9c18a192-fc54-11e7-8740-1c5c36fab6a9.png">

or the react favicon (64x64):

<img width="89" alt="screen shot 2018-01-18 at 1 34 52 pm" src="https://user-images.githubusercontent.com/179361/35117561-9e7dfb12-fc54-11e7-80f4-b667fcdbf604.png">

or the wikipedia icon (48x48):

<img width="84" alt="screen shot 2018-01-18 at 1 35 00 pm" src="https://user-images.githubusercontent.com/179361/35117566-a0965cf0-fc54-11e7-8776-48091908fc1e.png">

It looks like this might be happening because [the calculations of where to put the alertCount are static pixels](https://github.com/oflisback/react-favicon/blob/master/lib/react-favicon.js#L17-L21) which don't scale with the image size.

**Comment by oflisback** [comment]
Thanks @christiangenco, a pull request would be very welcome .. :)

**Comment by paulgreg** [comment]
I tried to do that PR but was blocked on build process.
The `build` command generates the `dist/react-favicon.js` file with `require` causing an error in the browser (see https://github.com/oflisback/react-favicon/blob/master/dist/react-favicon.js#L11).
Note that this file is not the one from the live example : http://oflisback.github.io/react-favicon/dist/react-favicon.js
So it seems that a webpack step is missing in the build process.
Could you tell me please how to build a version working on browser, to be able to test the library from the index.html page please ?

**Comment by oflisback** [comment]
Hi @paulgreg glad you are looking into it! I believe the intention here is that the consuming project's bundler, such as webpack, does the necessary transformations. Try this search for instance to find many projects that include it as a part of their build process [https://github.com/search?q=import+react-favicon&type=Code](https://github.com/search?q=import+react-favicon&type=Code).

**Comment by oflisback** [comment]
Thanks a lot @paulgreg! It's now in the 0.0.18 version of react-favicon.
