### ISSUE TITLE
Problem online example

### ISSUE THREAD

**Issue by Angelk90** [oflisback/react-favicon#26]
Hi @oflisback , 

Congratulations on a great project, I tried the online example but it doesn't seem to work properly.

This is what I see at the moment using, mac os and google chrome.
The number seems to be visible but it is very small and it is not inside the red part.

<img width="127" alt="Schermata 2021-03-19 alle 21 36 41" src="https://user-images.githubusercontent.com/20476002/111839686-753c7f80-88fb-11eb-987f-037cfb184997.png">

What I would like to be able to do is such a thing, would it be possible?
<img width="74" alt="Schermata 2021-03-19 alle 21 39 40" src="https://user-images.githubusercontent.com/20476002/111839781-a1580080-88fb-11eb-92a3-0fde948a8377.png">

**Comment by oflisback** [comment]
Hi @Angelk90,

thank you and sorry for the late response. I just had a chance to try this out myself with the MacOS/Chrome combo but in my case it looks as intended and similar to your third example. I updated the example today, please have a second look. It would be interesting to know if you have the same problem in other OS/Browser setups.

I'm considering adding a new prop that would take a function called by Favicon to let the user draw the overlay themselves for complete control.

**Comment by Angelk90** [comment]
@oflisback : 
I also got the same problem on linux with firefox or google chrome combination.
Trying it on mac os / google chrome, with a two digit number I get this:
<img width="108" alt="Schermata 2021-04-11 alle 17 27 25" src="https://user-images.githubusercontent.com/20476002/114310554-648ebc00-9aeb-11eb-9e85-d1a2c4ccde70.png">

**Comment by oflisback** [comment]
Thanks for the quick response, yes that's unfortunately the way it works for numbers >9. I'll add a new property and extend the example to let the user draw any type of overlay.

**Comment by oflisback** [comment]
Now version 0.0.20 is available where a new prop renderOverlay is added. It takes a function to render a custom overlay.

This is how it's used in the updated example:

```
      <Favicon
        renderOverlay={(canvas, context) => {
                const top = canvas.height - 9
                const left = canvas.width - 7 - 1
                const bottom = 16
                const right = 16
                const radius = 2

                context.fillStyle = 'green'
                context.strokeStyle = 'green'
                context.lineWidth = 1

                context.beginPath()
                context.moveTo(left + radius, top)
                context.quadraticCurveTo(left, top, left, top + radius)
                context.lineTo(left, bottom - radius)
                context.quadraticCurveTo(left, bottom, left + radius, bottom)
                context.lineTo(right - radius, bottom)
                context.quadraticCurveTo(right, bottom, right, bottom - radius)
                context.lineTo(right, top + radius)
                context.quadraticCurveTo(right, top, right - radius, top)
                context.closePath()
                context.fill()

                context.font = 'bold 10px arial'
                context.fillStyle = '#FFF'
                context.textAlign = 'right'
                context.textBaseline = 'top'
                context.fillText('a', 15, 6)
              }
        }
        {/* the other props */}
      />
```

**Comment by Angelk90** [comment]
@oflisback : I tried online example at http://oflisback.github.io/react-favicon, but I get the same result.

**Comment by oflisback** [comment]
Yes the behavior of alertCount is the same and I don't think it's worth improving that, but depending on what you need you can implement the overlay logic yourself now via the "renderOverlay" prop by writing your own function to draw any overlay you want.

**Comment by Angelk90** [comment]
@oflisback : This is my personal version, it solves many of the problems discussed above and others.
New props have been added, let me know if it can help you.

```javascript
const React = require('react');

let linkEl;

const faviconSize = 64;

CanvasRenderingContext2D.prototype.roundRect = function(sx, sy, ex, ey, r) {
	const r2d = Math.PI / 180;
	if (ex - sx - 2 * r < 0) {
		r = (ex - sx) / 2;
	} // ensure that the radius isn't too large for x
	if (ey - sy - 2 * r < 0) {
		r = (ey - sy) / 2;
	} // ensure that the radius isn't too large for y
	this.beginPath();
	this.moveTo(sx + r, sy);
	this.lineTo(ex - r, sy);
	this.arc(ex - r, sy + r, r, r2d * 270, r2d * 360, false);
	this.lineTo(ex, ey - r);
	this.arc(ex - r, ey - r, r, r2d * 0, r2d * 90, false);
	this.lineTo(sx + r, ey);
	this.arc(sx + r, ey - r, r, r2d * 90, r2d * 180, false);
	this.lineTo(sx, sy + r);
	this.arc(sx + r, sy + r, r, r2d * 180, r2d * 270, false);
	this.closePath();
};

function drawIcon(src, num, cb, fill, color, noCount, round) {
	const img = document.createElement('img');
	img.crossOrigin = 'Anonymous';
	img.onload = function() {
		const canvas = document.createElement('canvas');
		canvas.width = faviconSize;
		canvas.height = faviconSize;

		const context = canvas.getContext('2d');
		context.clearRect(0, 0, img.width, img.height);
		context.drawImage(img, 0, 0, canvas.width, canvas.height);

		const lenNum = num.toString().length;
		if (lenNum > 2) num = 99;
		const fattSx = lenNum > 1 ? 0.2 : 0.35;
		context.roundRect(faviconSize * fattSx, faviconSize * 0.5, faviconSize, faviconSize, round);
		context.fillStyle = fill;
		context.fill();

		if (!noCount) {
			context.font = 'bold 31px arial';
			context.fillStyle = color;
			context.textAlign = 'right';
			context.textBaseline = 'top';
			const fatt = lenNum > 1 ? 1.15 : 1.2;
			context.fillText(num, faviconSize / fatt, faviconSize / 1.8);
		}

		cb(null, context.canvas.toDataURL());
	};
	img.src = src;
}

class Favicon extends React.Component {
	static displayName = 'Favicon';

	static defaultProps = {
		alertCount: null,
		animated: true,
		animationDelay: 500,
		keepIconLink() {
			return false;
		},
		fill: '#F03D25',
		color: '#FFFFFF',
		noCount: false,
		round: faviconSize / 2
	};

	static mountedInstances = [];

	static getActiveInstance() {
		return Favicon.mountedInstances[Favicon.mountedInstances.length - 1];
	}

	static draw() {
		if (typeof document === 'undefined') return;

		const activeInstance = Favicon.getActiveInstance();
		if (typeof linkEl === 'undefined') {
			const head = document.getElementsByTagName('head')[0];
			linkEl = document.createElement('link');
			linkEl.type = 'image/x-icon';
			linkEl.rel = 'icon';

			// remove existing favicons
			const links = head.getElementsByTagName('link');
			for (let i = links.length; --i >= 0; ) {
				if (/\bicon\b/i.test(links[i].getAttribute('rel')) && !activeInstance.props.keepIconLink(links[i])) {
					head.removeChild(links[i]);
				}
			}

			head.appendChild(linkEl);
		}

		let currentUrl;

		if (activeInstance.props.url instanceof Array) {
			currentUrl = activeInstance.props.url[activeInstance.state.animationIndex];
		} else {
			currentUrl = activeInstance.props.url;
		}

		if (activeInstance.props.alertCount) {
			drawIcon(
				currentUrl,
				activeInstance.props.alertCount,
				function(err, url) {
					linkEl.href = url;
				},
				activeInstance.props.fill,
				activeInstance.props.color,
				activeInstance.props.noCount,
				activeInstance.props.round
			);
		} else {
			linkEl.href = currentUrl;
		}
	}

	static update() {
		if (typeof document === 'undefined') return;

		const activeInstance = Favicon.getActiveInstance();
		const isAnimated = activeInstance.props.url instanceof Array && activeInstance.props.animated;

		// clear any running animations
		let intervalId = null;
		clearInterval(activeInstance.state.animationLoop);

		if (isAnimated) {
			const animateFavicon = function animateFavicon() {
				const nextAnimationIndex = (activeInstance.state.animationIndex + 1) % activeInstance.props.url.length;
				Favicon.draw();
				activeInstance.setState({ animationIndex: nextAnimationIndex });
			};
			intervalId = setInterval(animateFavicon, activeInstance.props.animationDelay);
			animateFavicon();
		} else {
			Favicon.draw();
		}

		activeInstance.setState({ animationLoop: intervalId });
	}

	state = {
		animationIndex: 0,
		animationLoop: null,
		animationRunning: false
	};

	componentDidMount() {
		Favicon.mountedInstances.push(this);
		Favicon.update();
	}

	componentWillUnmount() {
		const activeInstance = Favicon.getActiveInstance();
		clearInterval(activeInstance.state.animationLoop);
	}

	componentDidUpdate(prevProps) {
		if (
			prevProps.url === this.props.url &&
			prevProps.animated === this.props.animated &&
			prevProps.alertCount === this.props.alertCount &&
			prevProps.keepIconLink === this.props.keepIconLink &&
			prevProps.fill === this.props.fill &&
			prevProps.color === this.props.color &&
			prevProps.noCount === this.props.noCount &&
			prevProps.round === this.props.round
		)
			return;
		Favicon.update();
	}

	render() {
		return null;
	}
}

// module.exports = Favicon;
export default Favicon;
```

**Comment by Angelk90** [comment]
@oflisback : At the moment I can't, but all the changes that have been made, there is a reason behind it, like the various props that have been added.

**Comment by oflisback** [comment]
I published version 0.0.21 with new props alertFillColor and alertTextColor, it also draws a much nicer rounded rectangle similar to yours. Thank you for suggestions and example implementation!

**Comment by Angelk90** [comment]
@oflisback : Is the demo version already online?

**Comment by oflisback** [comment]
Oops thanks, now it is.

**Comment by Angelk90** [comment]
@oflisback : Ok, I tried the online version.
Can I give you some considerations?

**Comment by oflisback** [comment]
sure thing, please do

**Comment by Angelk90** [comment]
@oflisback : 

Here is a list of suggestions:

1) When you add the badge to a favicon, it lowers the quality level of the image, then easily see it in the icon
wikipedia putting on and removing the badge, how the quality of it changes.
The solution I found as seen from the code I posted above, would be to increase the size of the `faviconSize` this way it seems that the problem is solved, obviously increasing the size you have to fix all the calculations that refer to it.

2) The idea of ​​having renderOverlay to insert the text is not bad, but if a text of two or three characters is entered, for example "Hi!" that seems to fit, the background of the badge only takes one character.
It is up to the user to work on this function but it would not be bad, try to fix the function using `ctx.measureText(text) .width` for example.

3) It would be interesting to have the option to have a badge as seen in image two, without numbers or text, but it is indicating that an event has happened.
For example the `noCount` of my props, but by adjusting the ui, as in the image below.
![](https://user-images.githubusercontent.com/20476002/111839781-a1580080-88fb-11eb-92a3-0fde948a8377.png)

4) Two properties that in my opinion would be interesting are, the possibility of having a `non-rounded badge` if the user does not want to have a round value by default, having to set the round value to the user in case.
Define a prop that is used to understand what the function should do when a certain value is reached.
Example for me, when the number exceeds two digits I only show `99`, because three-digit numbers give problems.

```javascript
const lenNum = num.toString().length;
if (lenNum> 2) num = 99;
```

These are just suggestions.

**Comment by oflisback** [comment]
Thanks for taking your time to do this, my opinions on the suggestions:

1: I will look into and fix this for sure, nice find!
2: renderOverlay draws the background too so it's possible to extend it if needed and if the regular alert overlay isn't sufficient.
3: This can be done either with renderOverlay or by passing a special character in alertCount which now also accepts strings, but to not mess with backwards compatibility the prop name was left unchanged.
4: I don't think we should focus on solving such things in react-favicon, renderOverlay should be sufficient for additional overlay customization.
