### ISSUE TITLE
Upgrade peerDependencies

### ISSUE THREAD

**Issue by Redirts** [oflisback/react-favicon#27]
"peerDependencies": {
    "react": "^16.0.0 || ^17.0.0"
  }

version 17.0.2 of React is out already. Maybe you can change the semver check to 17.0?

Thanks

**Comment by oflisback** [comment]
I think we're fine with that peerDependencies value, you can validate semver strings here:
 
https://jubianchi.github.io/semver-check/#/%20^16.0.0%20||%20^17.0.0/17.0.2

**Comment by Redirts** [comment]
Strange because I am getting this warning on npm install:

npm WARN react-favicon@0.0.18 requires a peer of react@>=0.12.0 <17.0.0 but none is installed. You must install peer dependencies yourself.

I have react 17.0.1

**Comment by oflisback** [comment]
Ah ok, with version 0.0.18 the peerDependencies value was different:

https://github.com/oflisback/react-favicon/blob/20873272d28cb877e8f177272ccdd06c9d8fc523/package.json

**Comment by Redirts** [comment]
Ah! Mystery solved :-) I didn't notice it had changed. I will upgrade then and close this ticket. Thanks
