### ISSUE TITLE
can URL accept images path within the web project?

### ISSUE THREAD

**Issue by rsabishek** [oflisback/react-favicon#30]
should the URL parameter be given only in HTTP:// form or can we mention the relative path of the image as well in the Favicon props?

**Comment by oflisback** [comment]
You can use image assets available in your project too, if your bundler supports it. For example if you use create-react-app this will work out of the box. Have a look at how it's done in the example where a favicon is referenced via "img/github.ico":

https://github.com/oflisback/react-favicon/blob/master/example/src/App.js
