### ISSUE TITLE
2.0.4 causes constant rerenders

### ISSUE THREAD

**Issue by bmcallis** [oflisback/react-favicon#56]
[Defaulting](https://github.com/oflisback/react-favicon/blob/1cc97fe9a08ffd8fdf155de23b50b27ac8d261cb/src/index.jsx#L123) `keepIconLink` to a function when destructing the props causes constant rerenders when it's not set as a prop.

**Comment by steven-cole-elliott** [comment]
I just upgraded to 2.0.4 and am also experiencing this issue.

**Comment by oflisback** [comment]
Thanks a lot for reporting this, I have reverted the offending commit to investigate offline, there's a new `2.0.5` version published.
